### ISSUE TITLE
Overlay not loaded

### ISSUE THREAD

**Issue by jvlars** [28757B2/cc1101-driver#1]
Hi,

I'm having some problems installing the cc1101-driver, I've followed the procedure but can't get the overlay loaded.
FIrst: When trying to insert the module I get the below message:
pi@raspberrypi:~/cc1101-driver $ sudo insmod cc1101.ko
insmod: ERROR: could not insert module cc1101.ko: Device or resource busy

The insmod command is working after a reboot and can see it loaded with lsmod. 

Second:
The cc1101 overlay is not loading. I can't see the expected /dev/cc1101.x.x.
Also the /dev/spidev0.x is also gone.
After removing the /boot/overlays/cc1101.dtbo the spidev0.x appears again and is working fine.
When I try to add the overlay I get the below message:
pi@raspberrypi:~/cc1101-driver $ sudo dtoverlay -v /boot/overlays/cc1101.dtbo
DTOVERLAY[debug]: using platform 'bcm2835'
DTOVERLAY[debug]: overlay map loaded
run_cmd: which dtoverlay-pre >/dev/null 2>&1 && dtoverlay-pre
DTOVERLAY[debug]: loading file '/boot/overlays/cc1101.dtbo'
DTOVERLAY[debug]: wrote 2026 bytes to '/tmp/.dtoverlays/0_cc1101.dtbo'
DTOVERLAY[debug]: wrote 2026 bytes to '/sys/kernel/config/device-tree/overlays/0_cc1101/dtbo'
* Failed to apply overlay '0_cc1101' (kernel)
run_cmd: which dtoverlay-post >/dev/null 2>&1 && dtoverlay-post

dmesg:
[  238.440197] OF: overlay: WARNING: memory leak will occur if overlay removed, property: /soc/spi@7e204000/spidev@0/status
[  238.440233] OF: overlay: WARNING: memory leak will occur if overlay removed, property: /soc/spi@7e204000/spidev@1/status
[  238.440266] OF: overlay: WARNING: memory leak will occur if overlay removed, property: /soc/spi@7e204000/pinctrl-names
[  238.440290] OF: overlay: WARNING: memory leak will occur if overlay removed, property: /soc/spi@7e204000/pinctrl-0
[  238.440314] OF: overlay: WARNING: memory leak will occur if overlay removed, property: /soc/spi@7e204000/cs-gpios

Any tips? Am I missing some dependencies or wrong version?

**Comment by 28757B2** [comment]
Hi,

You should just need to add the `dtoverlay=cc1101` line to `/boot/config.txt`, reboot, then run `insmod cc1101.ko`. After running insmod, something like this should appear when doing a dmesg:

```
[  219.554959] cc1101 spi0.1: Device not found
[  219.558774] cc1101 spi0.0: Ready
```

If /dev/spidev0.x is disappearing, then the overlay is working. The overlay has to disable the spidev driver, as the cc1101 driver and spidev can't both claim the SPI device at the same time. The error messages when doing `insmod cc1101.ko`/`dtoverlay -v /boot/overlays/cc1101.dtbo` are because the spidev driver has already been loaded, so the overlay needs to be applied at boot to disable spidev before it claims the device.

**Comment by jvlars** [comment]
Thank you for your explanation.

The problem is that I don't get the /dev/cc1101.x.x device.
I did what you mentioned and checked dmesg after the "insmod cc1101.ko"
For some reason I'm getting a device not found on both spi's, that is probably why I don't get /dev/cc1101.x.x

[   46.732214] cc1101: loading out-of-tree module taints kernel.
[   46.736816] cc1101 spi0.1: Device not found
[   46.737248] cc1101 spi0.0: Device not found

Any idea why that happens? Or where I can check to get more details?
spidev is working fine with cc1101 on a different project, ref https://github.com/aviborg/MonitorKNXRF

**Comment by 28757B2** [comment]
I suspect this might be to do with the part/version number of the CC1101 chip you have. Looking at the other project, its using a less strict check for the version number than I am, so I probably need to relax this check.

Could you retry with the latest master branch and re-post your dmesg output please? I've changed the code to log the part and version numbers. If that's the cause I'll add them to the values that are allowed.

Thanks

**Comment by jvlars** [comment]
See the below dmesg output:

[    6.969129] cc1101 spi0.1: Device not found (Partnum: 0x00, Version: 0x00)
[    6.972304] cc1101 spi0.0: Device not found (Partnum: 0x00, Version: 0x04)

**Comment by 28757B2** [comment]
Thanks, that does look like the cause of the issue. 3b9d61622ee1654dd19914082c1834390484ea22 will allow that version number now.

**Comment by jvlars** [comment]
Thank you for the update and help on this! I now get the /dev/cc1101.x.x and can run the software
