### ISSUE TITLE
Packets longer than 64 bytes are sent partially

### ISSUE THREAD

**Issue by wasilukm** [28757B2/cc1101-driver#3]
Long packets are not sent completely, "tail" is trimmed.

How to reproduce:
1. Try to transmit for example 656 bytes of data
2. Observe debug output, observe transmitted data (it is enough to measure transmission time with some receiver like RTL SDR)

Observed:
- tx underflow in the debug output
- transmission time shorter than expected

Probable root cause:
It seems that packet remainder in[ tx_multi()](https://github.com/28757B2/cc1101-driver/blob/df87b9a32d1838361ff49270f23b0e95705cad84/cc1101_radio.c#L149) is written to TX FIFO too early without making sure that there is a place for it. This causes TX FIFO corruption and transmission cancelation.

**Comment by 28757B2** [comment]
Thanks for the report and tracking this down. Writing to the TX FIFO too early does look very likely to be the cause. I'll do some investigation and get it fixed.

**Comment by 28757B2** [comment]
This should be fixed now in [d484066](https://github.com/28757B2/cc1101-driver/commit/d4840666bd8343ceb2d0f56a93347b4141988e58)

**Comment by wasilukm** [comment]
I confirm, thank you! I seems that you have also improved packet fragmentation. It looks now more in line with CC1101 spec. Great!
